### ISSUE TITLE
Custom databox directory ignored

### ISSUE THREAD

**Issue by drudv** [dfridrich/CzechDataBox#1]
Having

```
$dataBox = new DataBox('/my/custom/data-box');
```
files are being saved to the root and the provided custom directory path is ignored. Looks like it is not even stored in `directory` property of `DataBox` here:

https://github.com/dfridrich/CzechDataBox/blob/05e03b3d27b99b0aef294462497bf9fcbff968f9/src/DataBox.php#L68

**Comment by dfridrich** [comment]
Hi, can you provide fix?

**Comment by drudv** [comment]
I've just sent a PR #2 with the simple fix, that resolves my problem.
