### ISSUE TITLE
Neprijemna zkusenost PHP 8.2

### ISSUE THREAD

**Issue by meesha81** [dfridrich/CzechDataBox#9]
Bohuzel ani na konci dubna neni s PHP 8.2 kompatibilni. Update sice probehl, ale nic z nahlasenych konkretnich veci opraveno dosud nebylo. A to jsem panovi poslal nekolik tisic jako prispevek na vyvoj. Dlouhou dobu nekomunikuje a nikde nic. Mrzi me neseriozni pristup autora.

**Comment by zgruza** [comment]
Problém je ve vaší nechopnosti detekovat problémy. (Čehož by jste jako developer měl být schopný)
Stačí jít po Error Logu a zjistit co je špatně. Já osobně to spustil bez problému asi do 3 minut.

Jak?
1. Nainstaluj rozšíření soap: _apt-get install php8.0-soap_ (8.0 píšu, protože mám vícero verzí a v souboru .php-version vidím podporu primárně pro verzi 8.0)
2. Spusť composer pod verzí 8.0: _php8.0 /usr/local/bin/composer install_ (případně update)
3. Změň login na Datovku a otestuj: php8.2 ./examples/information_about_databox.php

Hotovo! 👍

**Comment by meesha81** [comment]
To asi nechápete správně, možná je to vaše neschopnost chápat souvislosti, ale to bych si vymýšlel obdobně jako vy. Kompatibility issues byly konkrétně nahlášené, nezbývá než si je "u sebe" opravit sám, protože tady se oprava neobjevila. A za druhé bylo přes x měsíci slíbeno, že se objeví nová verze co bude umět stáhnou přílohy odeslaných zpráv a také nic. Prostě autor vzal peníze, asi na tom něco udělal, ale v zásadě se neodstranila jediná reportovaná chyba plus nelze stahovat zprávy. Holt každý není poctivý a pokud by mi autor napsal že na tom dělat nebude, tak to budu respektovat. Jelikož napsal že to udělá, nabídl jsem mu že mu za to něco pošlu. Holt je toto zřejmě mrtvý projekt.

**Comment by meesha81** [comment]
No, to bych rád, ale vzhledem k tomu že to trvá od 15.1.2023 tak je to 5 měsíců co trvá těch "14 dnů". Zapírání, nekomunikace prostě značí jen lhaní do vlastní kapsy. Dospělí by to měli mít v hlavě asi srovnané. Já nikomu neupírám, že může/nemusí být čas a jsem extrémně vstřícný a trpělivý. Bohužel autor pokud na to nemá čas, tak měl rovnou naspat že na to nemá čas a ne jen "vstřícně" slibovat a vlastně výsledek nikde... Tak uvidíte, v tuto chvíli je to v rovině obrovské neserióznosti autora. Já ho k ničemu nenutil, jen jsem se ho zeptal.

**Comment by dfridrich** [comment]
Dobry den, neco se na tom skutecne udelalo, ale pokud to nesplnilo ocekavani, penize vam dnes posilam zpet. A ano, nemam cas, jsem zavaleny, omlouvam se. Kdyby kdokoli chtel, muze se o tuhle knihovnu starat, pripadne poslat PR, sily vitany :-) cc @meesha81

**Comment by tomas-kulhanek** [comment]
@dfridrich Což takhle spojit síly? :) mám taky knihovnu, co budu nyní aktualizovat o ty chujoviny co tam zavedli za poslední rok
